### ISSUE TITLE
Bounding Box information

### ISSUE THREAD

**Issue by spinoza1791** [sgjava/motiondetector#3]
How can I get the bounding box coordinates to output to a text file, along with the frames captured to the Motion folder?

**Comment by sgjava** [comment]
If you want to save every frames motion metadata then there's a couple of ways. One would be to add the code to motiondet.py in the [detect](https://github.com/sgjava/motiondetector/blob/3fbb8cce81cfcee1b6442157aa3d7b0c5d363e4d/codeferm/motiondet.py#L52) method, but that would change its generic nature. The correct way would be to add a notifyObservers on each frame processed by the detect method. You have to add the new event attribute to [config](https://github.com/sgjava/motiondetector/blob/3fbb8cce81cfcee1b6442157aa3d7b0c5d363e4d/codeferm/config.py#L22) class, write a simple plugin using a simple one like [healthcheck.py](https://github.com/sgjava/motiondetector/blob/master/codeferm/healthcheck.py) as a reference.

You need to keep the performance good, so you could probably keep the data in memory using a dict with frame number as key and metadata as value. Then kick off a thread to write it off when you get a motionStop event.

Using notifyObservers allows the videoloop to see all motion events.

**Comment by sgjava** [comment]
Closing this out as a DIY request.
